### ISSUE TITLE
How to avoid opening a tab when connecting to existing browser

### ISSUE THREAD

**Issue by erkannt** [rust-headless-chrome/rust-headless-chrome#392]
When I connect to an already open browser I always get a new tab.

`Browser::connect(debug_ws_url)`

Is this expected? Can I avoid it?

**Comment by dimchee** [comment]
Tab opening on new chrome instance is hardcoded, I am making `PR` to solve it, hopefully it will be accepted

**Comment by dimchee** [comment]
You can try using my branch, by adding this to your `Cargo.toml`
```toml
[dependencies]
headless_chrome = { git = "https://github.com/dimchee/rust-headless-chrome.git" }
```
